hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
      - /users/money/**
  db:
    database: hm-user
  swagger:
    title: 用户服务接口文档
    package: com.hmall.user.controller
feign:
  okhttp:
    enabled: true # 开启okhttp的feign底层请求调用客户端okhttp