
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/json;

    sendfile        on;
    keepalive_timeout  65;

    # ========== 用户端 (Portal) ==========
    server {
        listen       18080;

        # 前端静态页面
        location / {
            root /usr/share/nginx/html/hmall-portal;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # API 代理到 Spring Cloud Gateway
        location /api {
            rewrite /api/(.*)  /$1 break;
            proxy_pass http://host.docker.internal:8080;
        }
    }

    # ========== 管理端 (Admin) ==========
    server {
        listen       18081;

        # 前端静态页面
        location / {
            root /usr/share/nginx/html/hmall-admin;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # API 代理到 Spring Cloud Gateway
        location /api {
            rewrite /api/(.*)  /$1 break;
            proxy_pass http://host.docker.internal:8080;
        }
    }
}
