# TODO
# 可以将该段抽取出来，使用nacos统一配置管理
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
  db:
    database: hm-pay
  swagger:
    title: 支付服务接口文档
    package: com.hmall.pay.controller
feign:
  okhttp:
    enabled: true # 开启okhttp的feign底层请求调用客户端okhttp
spring:
  rabbitmq:
    host: ${hm.mq.host:localhost} # 主机地址，Docker中通过环境变量覆盖
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: itheima # 用户名
    password: 123321 # 密码
